const ProjectItems = [
  {
    link: "https://karinkaaa.github.io/pokedex/",
    title: "Pokedex",
    subtitle: "Pokemon characters viewer web application",
    technologies: [
      "TypeScript",
      "React",
      "Redux",
      "Redux Toolkit",
      "Material UI",
      "HTML",
      "CSS",
    ],
  },
  {
    link: "https://karinkaaa.github.io/github-board/",
    title: "Github Board",
    subtitle: "GitHub repo issues viewer",
    technologies: [
      "TypeScript",
      "React",
      "Redux",
      "Redux Toolkit",
      "React Infinite Scroll",
      "Ant Design",
      "HTML",
      "CSS",
    ],
  },
  {
    link: "https://karinkaaa.github.io/todo-list/",
    title: "Todo List",
    subtitle: "Web application for task management",
    technologies: [
      "TypeScript",
      "React",
      "React Hook Form",
      "Redux",
      "Redux Toolkit",
      "Material UI",
      "HTML",
      "CSS",
    ],
  },
  {
    link: "https://rick-and-morty-characters-web.netlify.app/",
    title: "Rick And Morty",
    subtitle: "Rick and Morty characters viewer web application",
    technologies: [
      "TypeScript",
      "React",
      "React Router",
      "Redux",
      "Redux Toolkit",
      "Material UI",
      "HTML",
      "CSS",
      "Google OAuth2",
    ],
  },
  {
    link: "https://karinkaaa.github.io/News/",
    title: "News",
    subtitle: "Integration with an external server",
    technologies: [
      "JavaScript",
      "React",
      "Redux",
      "Redux Saga",
      "Material UI",
      "HTML",
      "CSS",
    ],
  },
  {
    link: "https://karinkaaa.github.io/portfolio/",
    title: "Portfolio",
    subtitle: "Development of my portfolio site",
    technologies: [
      "JavaScript",
      "THREE.js",
      "React",
      "Material UI",
      "HTML",
      "CSS",
    ],
  },
  {
    link: "https://karinkaaa.github.io/Stamina/",
    title: "Stamina",
    subtitle: "Online program for mastering ten-finger typing and touch typing",
    technologies: ["JavaScript", "React", "Material UI", "HTML", "CSS"],
  },
  {
    link: "https://karinkaaa.github.io/spin-admin-deploy",
    title: "Spin Admin",
    subtitle: "Development of the admin part for the Spinner game",
    technologies: [
      "JavaScript",
      "React",
      "Redux",
      "Redux Saga",
      "Mirage.js",
      "Faker",
      "Material UI",
      "HTML",
      "CSS",
    ],
  },
  {
    link: "https://karinkaaa.github.io/Products-front/",
    title: "Products",
    subtitle: "Home project for learning JavaScript, React and Redux",
    technologies: [
      "JavaScript",
      "React",
      "Redux",
      "Redux Saga",
      "Material UI",
      "HTML",
      "CSS",
    ],
  },
];

export default ProjectItems;
